# Generated by Django 6.1 on 2026-09-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='freelancer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
